export let States = [
  { label: "Andhra Pradesh", value: "Andhra Pradesh" },
  { label: "Arunachal Pradesh", value: "Arunachal Pradesh" },
  { label: "Assam", value: "Assam" },
  { label: "Bihar", value: "Bihar" },
  { label: "Chhattisgarh", value: "Chhattisgarh" },
  { label: "Goa", value: "Goa" },
  { label: "Gujarat", value: "Gujarat" },
  { label: "Haryana", value: "Haryana" },
  { label: "Himachal Pradesh", value: "Himachal Pradesh" },
  { label: "Jharkhand", value: "Jharkhand" },
  { label: "Karnataka", value: "Karnataka" },
  { label: "Kerala", value: "Kerala" },
  { label: "Madhya Pradesh", value: "Madhya Pradesh" },
  { label: "Maharashtra", value: "Maharashtra" },
  { label: "Manipur", value: "Manipur" },
  { label: "Meghalaya", value: "Meghalaya" },
  { label: "Mizoram", value: "Mizoram" },
  { label: "Nagaland", value: "Nagaland" },
  { label: "Odisha", value: "Odisha" },
  { label: "Punjab", value: "Punjab" },
  { label: "Rajasthan", value: "Rajasthan" },
  { label: "Sikkim", value: "Sikkim" },
  { label: "Tamil Nadu", value: "Tamil Nadu" },
  { label: "Telangana", value: "Telangana" },
  { label: "Tripura", value: "Tripura" },
  { label: "Uttar Pradesh", value: "Uttar Pradesh" },
  { label: "Uttarakhand", value: "Uttarakhand" },
  { label: "West Bengal", value: "West Bengal" },
];

export let Districts = [
  { label: "Ahmednagar", value: "Ahmednagar" },
  { label: "Akola", value: "Akola" },
  { label: "Amravati", value: "Amravati" },
  { label: "Aurangabad", value: "Aurangabad" },
  { label: "Beed", value: "Beed" },
  { label: "Bhandara", value: "Bhandara" },
  { label: "Buldhana", value: "Buldhana" },
  { label: "Chandrapur", value: "Chandrapur" },
  { label: "Dhule", value: "Dhule" },
  { label: "Gadchiroli", value: "Gadchiroli" },
  { label: "Gondia", value: "Gondia" },
  { label: "Hingoli", value: "Hingoli" },
  { label: "Jalgaon", value: "Jalgaon" },
  { label: "Jalna", value: "Jalna" },
  { label: "Kolhapur", value: "Kolhapur" },
  { label: "Latur", value: "Latur" },
  { label: "Mumbai City", value: "Mumbai City" },
  { label: "Mumbai Suburban", value: "Mumbai Suburban" },
  { label: "Nagpur", value: "Nagpur" },
  { label: "Nanded", value: "Nanded" },
  { label: "Nandurbar", value: "Nandurbar" },
  { label: "Nashik", value: "Nashik" },
  { label: "Osmanabad", value: "Osmanabad" },
  { label: "Palghar", value: "Palghar" },
  { label: "Parbhani", value: "Parbhani" },
  { label: "Pune", value: "Pune" },
  { label: "Raigad", value: "Raigad" },
  { label: "Ratnagiri", value: "Ratnagiri" },
  { label: "Sangli", value: "Sangli" },
  { label: "Satara", value: "Satara" },
  { label: "Sindhudurg", value: "Sindhudurg" },
  { label: "Solapur", value: "Solapur" },
  { label: "Thane", value: "Thane" },
  { label: "Wardha", value: "Wardha" },
  { label: "Washim", value: "Washim" },
  { label: "Yavatmal", value: "Yavatmal" },
];
